### ISSUE TITLE
Link do guia para desenvolver com solana esta quebrado

### ISSUE THREAD

**Issue by beceluiz** [web3brasil/web3brasil#19]
O link do Guia completo de desenvolvimento full-stack com Solana, React, Anchor, Rust e Phantom esta dando 404:

![image](https://user-images.githubusercontent.com/97623324/170391568-e51987b3-9c2e-4ea1-bf7b-90e2d67c341a.png)

**Comment by daniloab** [comment]
cc @vit0rr

**Comment by vit0rr** [comment]
Boa, vou arrumar

**Comment by vit0rr** [comment]
@beceluiz Arrumei https://github.com/web3brasil/web3brasil/blob/main/README.md#solana
Bons estudos e qqr coisa pode me marcar ;)
